services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: test
      POSTGRES_DB: urldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  pgdata: