services:
  #  nginx:
  #    image: nginx:latest
  #    ports:
  #      - "8080:80"
  #    depends_on:
  #      - backend
  backend:
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/urldb
  db:
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: urldb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: