services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
volumes:
  pgdata: