services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      - db
      - redis
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
  db:
    image: postgres:latest
  redis:
    image: redis:latest