CREATE TABLE urls
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    long_url  VARCHAR(2048)                           NOT NULL,
    short_url VARCHAR(255),
    CONSTRAINT pk_urls PRIMARY KEY (id)
);

ALTER TABLE urls
    ADD CONSTRAINT uc_urls_short_url UNIQUE (short_url);